name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - source  # 触发分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          npm install hexo-cli -g
          npm install hexo-deployer-git --save

      - name: Generate Static Files
        run: |
          hexo clean
          hexo generate

      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.BLOGAUTO }}  # Token 需有 repo 权限
        run: |
          git config --global user.name "smallmayi"
          git config --global user.email "1591698916@qq.com"
          hexo deploy