name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - source  # 当推送到 source 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false  # 禁用子模块检查
          
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Hexo Git Deployer
        run: |
          npm install hexo-deployer-git --save
          npm install hexo-cli -g
          npm install hexo-renderer-pug hexo-renderer-stylus --save
      - name: Clean and Generate Static Files
        run: |
          hexo clean
          hexo generate
      - name: Configure Git
        run: |
          git config --global user.name 'smallmayi'
          git config --global user.email '1591698916@qq.com'
      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.BLOGAUTO }}
        run: |
          cd public/
          git init
          git add -A
          git commit -m "update by workflows"
          git remote add origin https://${{ secrets.BLOGAUTO }}@github.com/smallmayi/smallmayi.github.io.git
          git push origin HEAD:main -f
